apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-service
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sentiment
  selector:
    matchLabels:
      app: ai-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      