apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sentiment
  selector:
    matchLabels:
      app: sentiment-api
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
    